sudo: required
services:
  - docker

before_install:
  - docker build -t ankan07/docker-angular -f Dockerfile.dev .

script:
  - docker run ankan07/docker-angular npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-angular"
  env: "DockerAngular-env"
  bucket_name: "elasticbeanstalk-ap-south-1-766480370455"
  bucket_path: "docker-angular"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
