sudo: required
services:
  - docker

before_install:
  - docker build -t ankan07/docker-angular -f Dockerfile.dev .

script:
  - docker run ankan07/docker-angular npm run test

  deploy:
    provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: "docker-angular"


